// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalRAsAService.Infrastructure.Data;

namespace SignalRAsAService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SignalRAsAService.Core.Models.Snapshot", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AsOfDateTime");

                    b.Property<string>("Data");

                    b.Property<int>("Sequence");

                    b.HasKey("SnapshotId");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("SignalRAsAService.Core.Models.StoredEvent", b =>
                {
                    b.Property<Guid>("StoredEventId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aggregate");

                    b.Property<string>("AggregateDotNetType");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Data");

                    b.Property<string>("DotNetType");

                    b.Property<int>("Sequence");

                    b.Property<Guid>("StreamId");

                    b.Property<string>("Type");

                    b.Property<int>("Version");

                    b.HasKey("StoredEventId");

                    b.ToTable("StoredEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
